### ISSUE TITLE
custom curser gets hidden behind other elements

### ISSUE THREAD

**Issue by brycked** [Nxrix/Pixel-8#10]
the custom cursor goes behind text and the scroll bar when hovering over them

![image](https://github.com/Nxrix/Pixel-8/assets/92804487/0ce2f9f7-be84-42d2-9eda-40ce5de8f17d) ![image](https://github.com/Nxrix/Pixel-8/assets/92804487/1ce477c6-a197-4dde-9219-8e05cfb16fd3)

**Comment by Nxrix** [comment]
well yes 
the text editor is a html element but the cursor is in the canvas
I don't have any way to fix it for now but there are some options that i will try
1 - adding a second cursor on the screen.
2 - making the text editor inside the canvas like pico-8 that is a very complex work
