### ISSUE TITLE
old links are broken

### ISSUE THREAD

**Issue by brycked** [Nxrix/Pixel-8#11]
pixel-8 no longer starts for cart links created before the new sound update

**Comment by Nxrix** [comment]
if you take a look at the api you will simplify see that everything is changed and there are so many new functions so the old ones won't load but if you want you can send me the old encoded url and I'll update it for you!

**Comment by brycked** [comment]
wouldnt it be nice to be able to view old artworks, or will they forever be lost?

**Comment by brycked** [comment]
i think we should automatically transform old code, or keep backwards compatibility

**Comment by brycked** [comment]
why did the encoding change in the first place? there is no reason to put all the different scripts in one value

instead the different scripts for init, update and wave could all be put in their own parameters like `/?init=...&cart=...&wave=...`

**Comment by Nxrix** [comment]
the old encoding system had alot of problems
