### ISSUE TITLE
`console.log` doesnt print to the pixel-8 console

### ISSUE THREAD

**Issue by brckd** [Nxrix/Pixel-8#12]
### expected behaviour

the log command prints to the pixel-8 console similar to how returned values are printed

### actual behaviour
<img width="584" alt="image" src="https://github.com/Nxrix/Pixel-8/assets/92804487/0ad28ebb-0edf-48ca-b01f-61a1d9b33a76">

the logged value isnt printed into the pixel-8 console, but to the browser console instead

**Comment by brycked** [comment]
this could be solved by injecting a custom console or using a library like [jsLogger](https://github.com/sunnykgupta/jsLogger)

**Comment by Nxrix** [comment]
console is not created to work like that 
the console is for getting result of functions or variables that you write
so if you execute a function in console the function will run but the console will return undefined if the function is not returning anything

**Comment by brycked** [comment]
still its probably not the expected behaviour for most users
