### ISSUE TITLE
host dynamic assets

### ISSUE THREAD

**Issue by brckd** [Nxrix/Pixel-8#7]
dynamic sites can send dynamic responds depending on the sent request
this can be especially useful to host dynamic assets

**Comment by brycked** [comment]
note that the dynamic site couldnt be hosted on github pages, but rather on external hosts like [vercel](https://vercel.com), [netlify](https://netlify.com) or [railway](https://railway.app)

**Comment by brycked** [comment]
optionally there could be a separate branch to keep hosting the static website

**Comment by brycked** [comment]
as you have already suggested it would be smart to cache the rendered artworks on a media storage provider like [supabase](https://supabase.com)

**Comment by Nxrix** [comment]
limits are so much for free hosting and also now I'm going to focus on something else but if I got it figured out I'm gonna make it!
