### ISSUE TITLE
shorten cart urls

### ISSUE THREAD

**Issue by brckd** [Nxrix/Pixel-8#9]
the current card urls can become really long and are therefore limited by the url size

they could be shortened by generating random ids using the [crypto api](https://developer.mozilla.org/en-US/docs/Web/API/Crypto)
alternatively a short hash of the code could be generated using [cybr53](https://github.com/bryc/code/blob/master/jshash/experimental/cyrb53.js) or [crypto](https://nodejs.org/api/crypto.html#hashdigestencoding) to avoid duplicate cards

**Comment by brycked** [comment]
alternatively strings could be comoressed using [lz_string](https://github.com/pieroxy/lz-string)'s `compressToEncodedURIComponent`
